#!/usr/bin/env bash
# this script writes out 10 "Best school",but breaks on the 9th line to say hi , using while and if statement.

counter=1
while [ $counter -le 10 ]; do
 echo "Best School"
if [ $counter -eq 9 ]; then 
 echo "Hi"
fi
((counter++))
done
