#!/usr/bin/env bash
# this script will break at 4th line to say "bad luck" and on the 8th to say"good luck" otherwise Best school

counter=1

while [ "$counter" -le 10 ]; do
if [ "$counter" -eq 4 ]; then
 echo "bad luck"
elif [ "$counter" -eq 8 ]; then 
 echo " good luck"
else
 echo "Best School"
fi
 ((counter++))
done
