#!/usr/bin/env bash
# This script integrate while loop with switch case control structures to write out 20 lines .

counter=1

while [ "$counter" -le 20 ]; do
 echo "$counter"
case "$counter" in
 4)
 echo "bad luck from China";;
 9)
 echo "bad luck from Japan";;
 17)
 echo "bad luck from Italy";;
esac
 ((counter++))
done
