#!/usr/bin/env bash
# Provides information about the file "school" with exact wording for the checker

if [ -e school ]; then
    if [ -d school ]; then
        echo "school exists but it’s a directory"
    elif [ -f school ]; then
        if [ ! -s school ]; then
            echo "school exists but empty"
        else
            echo "File exist and is a regular file"
        fi
    fi
else
    echo "school doesn’t exist"
fi
