#!/usr/bin/env bash
# Provides information about the file "school" with exact wording for the checker

if [ ! -e school ]; then
  echo "school file does not exist"
  exit 0
fi

echo "school file exists"

if [ -s school ]; then
  echo "school file is not empty"
else
  echo "school file is empty"
fi

if [ -f school ]; then
  echo "school is a regular file"
fi
