#!/usr/bin/env bash
# this script Creates the file /var/run/myscript.pid

PID_FILE="/var/run/myscript.pid"

# Create PID file
echo $$ > "$PID_FILE"

sigint_handler() {
    echo "Y U no love me?!"
}

sigterm_handler() {
    echo "I hate the kill command"
    rm -f "$PID_FILE"
    exit 0
}
sigquit_handler() {
    rm -f "$PID_FILE"
    exit 0
}

# Traps
trap sigint_handler SIGINT
trap sigterm_handler SIGTERM
trap sigquit_handler SIGQUIT

# Infinite loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done
