#!/usr/bin/env bash
# this script displays To infinity and beyond indefinitely.
# In each iteration of the loop there will be sleep 2.
while true
do
    echo "To infinity and beyond"
    sleep 2
done
